### ISSUE TITLE
Cluster for printing and distributing code?

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#16]
Wisconsin, 1856:

SEc. 367. The secretary of state shall, forthwith, after the passage of. this act, cause six thousand copies thereof to be printed in a separate pamphlet, as session laws are
now printed, and he shall, as soon as said pamplet is
printed, distribute the same as the session laws are now
required to be distributed, by law, and the remaining
copies shall be retained in the office of the secretary of
state, to be sold at cost to any person desiring to purchase
the same, (not more than five copies to one person), and
it shall not be necestiry to print the [this] act in the
session laws.

Does something like this appear anywhere else?

**Comment by lmullen** [comment]
It appears in a few different places, but wasn't caught in a cluster, probably because we require a minimum number of documents in a cluster. Here is a list of all sections which have "to be printed," though some of these are on a different topic (which laws can be used in evidence).

AL1852-001560.txt
CA1872-015520.txt
CO1877-003870.txt
CT1879-000470.txt
FL1892-006310.txt
FL1892-006900.txt
GB1875-004210.txt
GB1875-008460.txt
GB1875-008510.txt
GB1875-008530.txt
HI1897-002010.txt
IN1843-006690.txt
IN1852-002690.txt
IN1852-002700.txt
KS1868-003720.txt
MT1895-018490.txt
NC1868-006810.txt
NC1868-006920.txt
NY1850-003910.txt
NY1850-019420.txt
NY1876-000230.txt
NY1879-000250.txt
OK1891-001970.txt
OK1893-004270.txt
OR1862-008900.txt
TX1855-009610.txt
VA1893-000250.txt
WI1856-003670.txt
WV1868-021590.txt
