### ISSUE TITLE
Standardize colors of codes in spectrograms

### ISSUE THREAD

**Issue by lmullen** [lmullen/civil-procedure-codes#30]
@kfunk074 Here is what I need from you to standardize the colors in the spectrograms. Can you please look through the spectrograms I've created. For each state I'm going to use the same color, then create shades of that color for the different states. I'll do my best to give the shades equal weight but I don't know if that's possible. Can you make a list of (1) the most important state to standardize the colors and (2) the primary code in each state? You can just say it's the earliest code in each state unless there is some reason to prefer a different one.

**Comment by kfunk074** [comment]
Not sure I completely understand this. You mean for each state you'll use the same color and then different shade for different codes intra-state? Don't know what equal weight in shades means.

New York is the most important state, and NY1850 the most important version. Within the New York family, NY1829 should ideally be a different color or on the opposite pole of the shade, since it's non-Field Code.

There aren't a lot of states with multiple codes in the other spectrograms. I think the rule should be that the primary code is the latest one. If NC is really borrowing from WI, it's likely the latest version in 1858, and 1856 is only ranked higher due to messy OCR, or, at most, it was consulted secondarily.

**Comment by lmullen** [comment]
That's all I need to know: treat the latest code as the primary, and break out NY1829, and also NY1879/NY1879 into separate colors.

**Comment by kfunk074** [comment]
It would be ideal if the color scheme could more or less coordinate with the choropleths. Can New York statutes have varying shades of gold/yellow/orange/brown, California and Far West reds, Midwest and Lower South greens, and Upper Midwest (OH, WI) blues?

**Comment by lmullen** [comment]
Yes, I completely agree. Because we have so many different possible codes
that could be represented, settling on the color scheme had to wait until
we decided which spectrographs we were actually going to use. But now is
the right time.

On Saturday, May 21, 2016, Kellen Funk notifications@github.com wrote:

> It would be ideal if the color scheme could more or less coordinate with
> the choropleths. Can New York statutes have varying shades of
> gold/yellow/orange/brown, California and Far West reds, Midwest and Lower
> South greens, and Upper Midwest (OH, WI) blues?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/lmullen/civil-procedure-codes/issues/30#issuecomment-220778691

## 

Lincoln Mullen, http://lincolnmullen.com
Assistant Professor, Department of History & Art History
George Mason University
