### ISSUE TITLE
Standardize Display of Spectrographs

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#34]
All the shorter codes display at the same size (at least on my browser/screen), same width, same typeface, and each individual box representing a section is the same size. There seems to be a cutoff on length, however, because the longer codes scrunch the width and rearrange the number of boxes per row. Can the longer codes (IA, NY1876) match the shorter on width and box size and just run longer down the page?

**Comment by lmullen** [comment]
I'm kind of surprised by this, because I thought I had it working the way
you want it to be instead of the way you describe. Can you please take a
screenshot of two that aren't the way you expect? I just want to make sure
where the problem lies.

On Saturday, May 21, 2016, Kellen Funk notifications@github.com wrote:

> All the shorter codes display at the same size (at least on my
> browser/screen), same width, same typeface, and each individual box
> representing a section is the same size. There seems to be a cutoff on
> length, however, because the longer codes scrunch the width and rearrange
> the number of boxes per row. Can the longer codes (IA, NY1876) match the
> shorter on width and box size and just run longer down the page?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/lmullen/civil-procedure-codes/issues/34

## 

Lincoln Mullen, http://lincolnmullen.com
Assistant Professor, Department of History & Art History
George Mason University

**Comment by kfunk074** [comment]
![bad1](https://cloud.githubusercontent.com/assets/11466170/15448912/ea79c25e-1f3c-11e6-82be-af9605b59975.jpg)
![bad2](https://cloud.githubusercontent.com/assets/11466170/15448911/ea79542c-1f3c-11e6-8e3f-38aef615ec0f.jpg)
![good](https://cloud.githubusercontent.com/assets/11466170/15448913/ea7bcc02-1f3c-11e6-9de7-168e5a07a5b7.jpg)

**Comment by kfunk074** [comment]
The third shot is good, just to be clear.

**Comment by lmullen** [comment]
Okay good. It's working like I expect. There are a standard number of cells
in each row. It's only compressing the width because of the height. All I
will need to do is set a figure height bigger for the longer codes. Thanks.

On Saturday, May 21, 2016, Kellen Funk notifications@github.com wrote:

> The third shot is good, just to be clear.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/lmullen/civil-procedure-codes/issues/34#issuecomment-220780089

## 

Lincoln Mullen, http://lincolnmullen.com
Assistant Professor, Department of History & Art History
George Mason University

**Comment by lmullen** [comment]
The widths should be corrected now. If you think there are any that are not correct, let me know. A few might have a bit of excess height, but that just affects the white space around the plot and can be easily cropped. In addition, I've put more cells in each row: now there are 50, which makes it easier to count how many sections are in a code.
