### ISSUE TITLE
Women Permitted to Practice

### ISSUE THREAD

**Issue by kfunk074** [lmullen/civil-procedure-codes#9]
From AK1900: SEC. 734. Hereafter women shall be permitted to practice law as
attorneys in the courts of said district upon the same terms and conditions as men.

Does something like this appear anywhere else? If it shows up more than a couple places, it may be worth tracing out in similar fashion as the blood quantum section.

**Comment by lmullen** [comment]
I don't think there are any other matches. In the list of section pairs, there are four matches.

```
Source: local data frame [4 x 4]

                a               b similarity dissimilarity
            (chr)           (chr)      (dbl)         (dbl)
1 AK1900-00007330 MN1851-00004000  0.0923695      0.907631
2 AK1900-00007330 NY1850-00005980  0.1400970      0.859903
3 AK1900-00007330 NY1853-00004370  0.1410790      0.858921
4 AK1900-00007330 OR1862-00011490  0.2891000      0.710900
```

All of those are genuine matches, since they deal with admission to practicing law, but none of them mentions women. 

I also couldn't find similar sections with a keyword search, though that doesn't rule out the possibility that they exist with different language.
